language: cpp
sudo: required
dist: xenial

os:
    - linux
    
compiler:
  - clang
  - gcc

install:
    - sudo add-apt-repository ppa:bitcoin/bitcoin -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libssl-dev libdb4.8-dev libdb4.8++-dev libminiupnpc-dev libqt4-dev libqrencode-dev qt4-qmake
    
script:
    - qmake "USE_DBUS=1" "USE_QRCODE=1" "USE_UPNP=1"
    - make
    - make check
    - sudo cp SpectreSecurityCoin-qt /usr/bin/SpectreSecurityCoin-qt
    - sudo cp share/pixmaps/spectresecuritycoin.png /usr/share/pixmaps/spectresecuritycoin-qt.png
    
branches:
    only:
    - master
